on: pull_request
name: Pull Request Test Runner
jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --version
    - run: npm i
    - run: node --version
    - run: npm i -g lerna
    - run: npx lerna bootstrap
    - run: lerna run lint
    - run: lerna run test
    - run: lerna run build --ignore zengine-plugin-docs
      env:
        CI: true